### ISSUE TITLE
HTML elements in the text

### ISSUE THREAD

**Issue by hapimp** [nohaelgendy/en-ar-demo#2]
Thanks a lot for creating this, super easy to get up and running! I'm struggling to get html elements into the text though, e.g. line breaks and links. My preferred way would be to add these in the .json file, but googling around it seems this is not the way it's done, and there's a potential risk for cross site scripting (in my case, though, there will be no way for the user to input text, so I think this would be a non issue).

Anyway: Do you know of an easy way to add html into the text? The suggested solutions I found googling are over my head, I'm afraid.

**Comment by nohaelgendy** [comment]
Hi hapimp, 

I'm sorry for the late reply, and thank you for your patience!

I'm glad you found the project easy to set up. Regarding your issue with adding HTML elements like line breaks and links in the JSON file, Did you try to include basic HTML tags directly in the JSON strings ? 

Like this: 

`{
  "en": {
    "welcome": "Welcome to our site!<br>Here is a <a href='https://google.com'>link</a>."
  }
}
`

Then, when you display the content on your webpage, you can use innerHTML in JavaScript to render the HTML properly:

`document.getElementById('welcome-message').innerHTML = translations['en'].welcome;
`

Since your project doesn't involve user input, this approach should be safe and straightforward. 
Let me know if you need more help with this or anything else!
